language: cpp

os:
  - linux

compile:
  - g++

addons:
  apt:
    sources:
      - ubuntu-sdk-team
      - ubuntu-toolchain-r-test
    packages:
      - qtdeclarative5-dev
      - qtbase5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
      - gcc-5
      - g++-5

before_install:
  - scripts/travis_osx.sh

install:
  - [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - scripts/travis_qmake.sh
  - make
  - cd tests
  - ./tests
